# Generated by Django 4.1.3 on 2022-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbase_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
