# Generated by Django 4.1.3 on 2022-11-20 18:27

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userbase_about_alter_userbase_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile/', validators=[accounts.validators.validate_file_size]),
        ),
    ]
