# Generated by Django 4.1.3 on 2022-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_city_remove_order_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
        migrations.AddField(
            model_name='order',
            name='intent',
            field=models.CharField(default='hi', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='secret',
            field=models.CharField(default='hi', max_length=255),
        ),
    ]
